services:
  web:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    # so that we don't build after each modification;
    # enables automatic sync between local & the docker env.
    volumes:
      - ./backend:/code
    # default command to run; can be overwritten by docker-compose explict command
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
