---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: docker compose run --rm web sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Run Linting with Flake8
        run: docker compose run --rm web flake8
