---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Login to DH
        uses: docker/login-action@v3
        with:
          username: ${{ variable.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: docker compose run --rm web sh -c "python manage.py test"

      - name: Lint with flake8
        run: docker compose run --rm web "flake8"
